Update NightLord tools

diff --git a/NightLord tools b/NightLord tools
--- a/NightLord tools
+++ b/NightLord tools
@@ -89,8 +89,16 @@ while true; do
             clear
             echo -e "${PURPLE}Starting MC-CB...${RESET}"
             sleep 1
-            cd mc
-            java -Xmx8196M -Xms8196M -jar Server.jar nogui
+
+            cd mc || {
+                echo -e "\033[1;31mFolder 'mc' not found!${RESET}"
+                echo
+                read -p "Press Enter to return to menu..."
+                continue
+            }
+
+            java -Xmx8196M -Xms8196M -jar server.jar nogui
+
             echo
             read -p "Press Enter to return to menu..."
             ;;
